theme: jekyll-theme-minimal
title: ModPlex
description: ModPlex is Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at dictum tortor. Integer rutrum enim lobortis nisi efficitur ullamcorper.
logo: logo.png
