baseURL = 'https://philip.mallegolhansen.com/'
languageCode = 'en'
title = 'Philip Mallegol-Hansen'
theme = 'anubis2'
paginate = 100

[permalinks]
posts = '/blog/:slug'

[taxonomies]
tag = 'tags'

[author]
name = 'Philip Mallegol-Hansen'

[sitemap]
    priority = 0.5
    changefreq = 'monthly'

[params]
colorTheme = "auto"
colorThemeSwitcher = true
rssAsSocialIcon = true
toc = false
readNextPosts = 0
dateFormat = "Jan 2 2006"

social = [
    { id = "email", url = "mailto:philip@mallegolhansen.com" },
    { id = "github", url = "https://github.com/Hanse00" },
    { id = "linkedin", url = "https://www.linkedin.com/in/philip-mallegol-hansen-534b1a91/" },
    { id = "mastodon", url = "https://mastodon.mallegolhansen.com/@philip" },
    { id = "steam", url = "https://steamcommunity.com/id/hanse00" }
]

[params.UmamiAnalytics]
enabled = true
id = 'f516ccf4-b76a-42cd-a2e1-7e95426f57e4'
url = 'https://us.umami.is/script.js'

[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
weight = 2
