baseURL = 'https://hanse00.github.io/'
languageCode = 'en'
title = 'Hanse00'
disableKinds = ['taxonomy', 'term']
theme = 'anubis2'

[author]
name = 'Philip Mallegol-Hansen'

[sitemap]
    priority = 0.5

[params]
colorTheme = "auto"
colorThemeSwitcher = true
rssAsSocialIcon = true
toc = false

social = [
    { id = "email", url = "mailto:philip@mallegolhansen.com" },
    { id = "github", url = "https://github.com/Hanse00" },
    { id = "linkedin", url = "https://www.linkedin.com/in/philip-mallegol-hansen-534b1a91/" },
    { id = "mastodon", url = "https://mastodon.mallegolhansen.com/@philip" },
    { id = "steam", url = "https://steamcommunity.com/id/hanse00" }
]

[params.UmamiAnalytics]
enabled = true
id = 'f516ccf4-b76a-42cd-a2e1-7e95426f57e4'
url = 'https://us.umami.is/script.js'
