name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  pages: write
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        uses: actions/configure-pages@v5
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy
        uses: actions/deploy-pages@v4
